#: THIS IS NOT JSON FILE IT'S PYTHON DICTIONARY

styles={
    "_4020": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":0,"y":0},
        "bgcolor": "transparent",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "ink": "true",
        "ink_color": "yellow",
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4021": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "scroll": "ALWAYS"
    },
    "_4028": {
        # "WIDGET_NAME": "CONTAINER_TEXT",
        "alignment": {"x":0,"y":0},
        "bgcolor": "white,0.23",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "border": {"l":{"w":4,"c":"white12"},"t":{"w":4,"c":"white12"},"r":{"w":4,"c":"white12"},"b":{"w":4,"c":"white12"}},
        "border_radius": {"bl":44,"br":44,"tl":44,"tr":44},
        "ink": "true",
        "ink_color": "red",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4029": {
        # "WIDGET_NAME": "CONTENT_TEXT",
        "size": 21,
        "value": "Servicios Gastronómicos",
        "weight": "bold"
    },
    "_4024": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":0,"y":0},
        "bgcolor": "transparent",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "ink": "true",
        "ink_color": "yellow",
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4025": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "scroll": "ALWAYS"
    },
    "_4032": {
        # "WIDGET_NAME": "CONTAINER_ROW",
        "alignment": {"x":-1,"y":0},
        "bgcolor": "black54",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":31,"br":31,"tl":31,"tr":31},
        "ink": "true",
        "ink_color": "cyan",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":0,"t":0,"r":0,"b":0},
    },
    "_4033": {
        # "WIDGET_NAME": "CONTENT_ROW",
        "scroll": "ALWAYS"
    },
    "_4036": {
        # "WIDGET_NAME": "CONTAINER_ELEVATEDBUTTON",
        "alignment": {"x":0,"y":0},
        "bgcolor": "transparent",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":31,"br":31,"tl":31,"tr":31},
        "ink": "true",
        "ink_color": "red",
        "margin": {"l":4,"t":4,"r":4,"b":4},
        "padding": {"l":0,"t":0,"r":0,"b":0},
    },
    "_4037": {
        # "WIDGET_NAME": "CONTENT_ELEVATEDBUTTON",
        "height": "28",
        # "text": "Capitulo 1",
    },
    "_4040": {
        # "WIDGET_NAME": "CONTAINER_ROW",
        "alignment": {"x":-1,"y":0},
        "bgcolor": "black54",
        # "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":25,"br":25,"tl":25,"tr":25},
        # "image_src": "test/proyect_name/proyect_name/assets/.comments",
        "ink": "true",
        "ink_color": "cyan",
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4041": {
        # "WIDGET_NAME": "CONTENT_ROW",
        "scroll": "ALWAYS"
    },
    "_4044": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":0,"y":0},
        "bgcolor": "white,0.4",
        "border": {"l":{"w":4,"c":"white12"},"t":{"w":4,"c":"white12"},"r":{"w":4,"c":"white12"},"b":{"w":4,"c":"white12"}},
        "border_radius": {"bl":25,"br":25,"tl":25,"tr":25},
        "height": "320",
        "image_fit": "cover",
        "image_opacity": "0.5",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        # "image_src": "test/proyect_name/proyect_name/assets/RestauranteALaCarta.png",
        "ink": "true",
        "ink_color": "yellow",
        "padding": {"l":6,"t":6,"r":6,"b":6},
        "shadow": {"spread_radius":0,"blur_radius":24,"color":"black87","offset":{"x":0,"y":0},"blur_style":"outer"},
        "width": "219"
    },
    "_4045": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "alignment": "spaceBetween",
        "horizontal_alignment": "center",
        "scroll": "ALWAYS"
    },
    "_4100": {
        # "WIDGET_NAME": "CONTAINER_ROW",
        "alignment": {"x":-1,"y":0},
        "bgcolor": "transparent",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "height": "",
        "ink": "true",
        "ink_color": "cyan",
        "padding": {"l":6,"t":6,"r":6,"b":6},
        "width": ""
    },
    "_4101": {
        # "WIDGET_NAME": "CONTENT_ROW",
        "scroll": "ALWAYS"
    },
    "_4108": {
        # "WIDGET_NAME": "CONTAINER_ICON",
        "alignment": {"x":0,"y":0},
        "bgcolor": "black,0.14",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":44,"br":44,"tl":44,"tr":44},
        "ink": "true",
        "ink_color": "red",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4109": {
        # "WIDGET_NAME": "CONTENT_ICON",
        "name": "star",
    },
    "_4104": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":1,"y":1},
        "bgcolor": "black54",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":20,"br":20,"tl":20,"tr":20},
        "height": "247",
        "ink": "true",
        "ink_color": "yellow",
        "padding": {"l":6,"t":6,"r":6,"b":6},
        "width": ""
    },
    "_4105": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "scroll": "auto"
    },
    "_4112": {
        # "WIDGET_NAME": "CONTAINER_TEXT",
        "alignment": {"x":0,"y":0},
        "bgcolor": "black,0.14",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":12,"br":12,"tl":12,"tr":12},
        "ink": "true",
        "ink_color": "red",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4113": {
        # "WIDGET_NAME": "CONTENT_TEXT",
        "size": 10,
        # "value": "1.4 La relaciu00f3n interdepartamental. Su importancia en el servicio.",
        "weight": "bold"
    },
    "_4056": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":0,"y":0},
        "bgcolor": "red",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":44,"br":44,"tl":44,"tr":44},
        "ink": "true",
        "ink_color": "yellow",
        "margin": {"l":8,"t":0,"r":8,"b":0},
        "padding": {"l":0,"t":0,"r":0,"b":0},
    },
    "_4057": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "scroll": "ALWAYS",
        # "wrap":True,
    },
    "_4084": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":0,"y":0},
        "bgcolor": "white,0.14",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "border": {"l":{"w":4,"c":"white12"},"t":{"w":4,"c":"white12"},"r":{"w":4,"c":"white12"},"b":{"w":4,"c":"white12"}},
        "border_radius": {"bl":25,"br":25,"tl":25,"tr":25},
        "ink": "true",
        "ink_color": "red",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4085": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "scroll": "ALWAYS"
    },
    "_4088": {
        # "WIDGET_NAME": "CONTAINER_TEXT",
        "alignment": {"x":0,"y":0},
        "bgcolor": "transparent",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "ink": "true",
        "ink_color": "red",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":6,"t":6,"r":6,"b":6},
    },
    "_4089": {
        # "WIDGET_NAME": "CONTENT_TEXT",
        "size": 13,
        "text_align": "left",
        "value": "1.1 Surgimiento y evolución de los servicios gastronómicos.",
        "weight": "bold"
    },
    "_4092": {
        # "WIDGET_NAME": "CONTAINER_ROW",
        "alignment": {"x":0,"y":0},
        # "bgcolor": "black12",
        "bgcolor": "white,0.23",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":20,"br":20,"tl":20,"tr":20},
        "height": "198",
        "ink": "true",
        "ink_color": "cyan",
        "margin": {"l":8,"t":8,"r":8,"b":20},
        "padding": {"l":0,"t":0,"r":0,"b":0},
        "width": ""
    },
    "_4093": {
        # "WIDGET_NAME": "CONTENT_ROW",
        "scroll": "ALWAYS",
        # "wrap": True,
    },
    "_4096": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":1,"y":1},
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "bgcolor": "black,0.6",
        "border": {"l":{"w":6,"c":"white38"},"t":{"w":6,"c":"white38"},"r":{"w":6,"c":"white38"},"b":{"w":6,"c":"white38"}},
        "border_radius": {"bl":20,"br":20,"tl":20,"tr":20},
        # "height": "300",

        # "image_fit": "cover",
        # "image_opacity": "0.2",
        # "image_src": "test/proyect_name/proyect_name/assets/ServicioCafeRestauranteLujo.png",
        # "ink": "true",
        # "ink_color": "yellow",
        "margin": {"l":2,"t":2,"r":2,"b":2},
        "padding": {"l":4,"t":4,"r":4,"b":4},
        # "shadow": {"spread_radius":0,"blur_radius":24,"color":"black87","offset":{"x":0,"y":0},"blur_style":"outer"},
        # "width": "240"

    },
    "_4097": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "scroll": "ALWAYS",
        "wrap": True,

    },
    "_4116": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":0,"y":0},
        "bgcolor": "red",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "ink": "true",
        "ink_color": "yellow",
        "margin": {"l":{"l":6,"t":6,"r":6,"b":6},"t":{"l":6,"t":6,"r":6,"b":6},"r":{"l":6,"t":6,"r":6,"b":6},"b":{"l":6,"t":6,"r":6,"b":6}},
        "padding": {"l":{"l":3,"t":3,"r":3,"b":3},"t":{"l":3,"t":3,"r":3,"b":3},"r":{"l":3,"t":3,"r":3,"b":3},"b":{"l":3,"t":3,"r":3,"b":3}},
    },
    "_4117": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "scroll": "ALWAYS",
        # "wrap": True,
    },
    "_4120": {
        # "WIDGET_NAME": "CONTAINER_COLUMN",
        "alignment": {"x":0,"y":0},
        # "bgcolor": "white",
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "ink": "true",
        "ink_color": "yellow",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":8,"t":8,"r":8,"b":8},
    },
    "_4121": {
        # "WIDGET_NAME": "CONTENT_COLUMN",
        "horizontal_alignment": "center",
        "wrap": True,
        "scroll": "ALWAYS"
    },
    "_4124": {
        # "WIDGET_NAME": "CONTAINER_TEXT",
        "alignment": {"x":-1,"y":0},
        "bgcolor": "white,0.05",
        "blur": {"sigma_x":40,"sigma_y":40,"tile_mode":"mirror"},
        "border": {"l":{"w":0,"c":"transparent"},"t":{"w":0,"c":"transparent"},"r":{"w":0,"c":"transparent"},"b":{"w":0,"c":"transparent"}},
        "border_radius": {"bl":12,"br":12,"tl":12,"tr":12},
        "ink": "true",
        "ink_color": "red",
        "margin": {"l":0,"t":0,"r":0,"b":0},
        "padding": {"l":6,"t":6,"r":6,"b":6},
        "width":240,
        "height":25,
    },
    "_4125": {
        # "WIDGET_NAME": "CONTENT_TEXT",
        "size": 10,
        # "value": "Ready to make your first app!!",
        "weight": "bold"
    }
}